name: app
type: ruby:2.5
disk: 1024
web:
  locations:
    "/":
      root: "_site"
      index:
        - index.html
      passthru: false
hooks:
  build: |
    gem install jekyll bundler
    jekyll build
    cd assets/semantic/
    npm install
