# Page settings
title: We are Sort

# Mail settings
hello_mail: hello@wearesort.co.uk
sales_mail: sales@wearesort.co.uk

# Social media settings
twitter: wearesort
instagram: wearesort
facebook: wearesort
vimeo: wearesort
pinterest: wearesort
soundcloud: wearesort
medium: wearesort
youtube: wearesort
linkedin: wearesort

# Build settings
markdown: kramdown

# Build inclusions
include: ["_pages"]

# Build exclusions
exclude:
  - README.md
  - assets/node_modules
  - assets/semantic/src
  - assets/semantic/tasks
  - assets/semantic/gulpfile.js
  - assets/package-lock.json
  - assets/semantic.json