- avatar: andrew.jpg
  name: Andrew Larcombe
  title: Technical Consultant
  bio: TBC
  skills: TBC • TBC • TBC • TBC • TBC

- avatar: andy.jpg
  name: Andy Switzer
  title: Consultant
  bio: TBC
  skills: TBC • TBC • TBC • TBC • TBC

- avatar: dan.jpg
  name: Dan Leakey
  title: Delivery Manager
  bio: Agile practitioner maximising team delivery. Spurs fan. Marvel comics nerd. Serial 10k runner.
  skills: Agile delivery, Product ownership, Scrum, Kanban, Project management

- avatar: desmond.jpg
  name: Desmond Hewitt
  title: Business Director
  bio: Advised various international orgs. 25+ years IT sales experience. Value-focused & outcome-lead.
  skills: Digital outcome value selling, Digital strategy & innovation, Strategic account management, Global service delivery & support, Executive program management

- avatar: garion.jpg
  name: Garion Woodcock
  title: Sales
  bio: TBC
  skills: TBC • TBC • TBC • TBC • TBC

- avatar: johan.jpg
  name: Johan Gant
  title: Lead Developer
  bio: 10+ yrs building web things. Fan of simple tech solving real-world problems. Once met a polar bear.
  skills: Technical architecture and consulting, Systems integration, Data migration, Drupal development, Performance analysis and engineering

- avatar: john.jpg
  name: John Durance
  title: Lead Developer
  bio: Built useful services to solve all kinds of problem, for all sectors. 5K runner. UK-based, sometimes Germany.
  skills: Content management systems, Data visualisation, Search, Online communities, Agile delivery

- avatar: karl.jpg
  name: Karl Orsborn
  title: Service Designer
  bio: TBC
  skills: TBC • TBC • TBC • TBC • TBC

- avatar: luke.jpg
  name: Luke Branford
  title: Director
  bio: Fell into digital 10+ yrs ago @ MTV. Driven change in private & public sectors. Mountain climber.
  skills: Digital strategy consulting, Product ownership, Digital project delivery, Analytics

- avatar: martin.jpg
  name: Martin Fraser
  title: Lead Developer
  bio: Working on the Internet since before the web existed. Once built a system in the North Sea.
  skills: Systems architecture, Software development, Drupal development, Systems integration

- avatar: mat.jpg
  name: Mat Matthews
  title: CEO
  bio: Tech industry veteran. Built fast scaling businesses. Hands-on. 20+ yrs in tech, sales & operations.
  skills: Building rapidly scaling businesses, Hands-on management, Outcomes sales, Business operations, Acquisitions and mergers

- avatar: no-image.jpg
  name: Nancy Roberts
  title: Job title
  bio: TBC
  skills: TBC • TBC • TBC • TBC • TBC

- avatar: olivier.jpg
  name: Olivier Severs
  title: Sales
  bio: Worn various digital hats. Helping businesses solve problems. Foodie & keen philanthropist.
  skills: Project management, Account management, Business development

- avatar: paul.jpg
  name: Paul Moloney
  title: Lead Developer
  bio: 10+ yrs in web development, front & back. Drupalista and open source techy. Worked with many sectors.
  skills: Drupal development, Data migration, Accessibility optimisation, Performance optimisation

- avatar: paulina.jpg
  name: Paulina Ziecik
  title: Office Manager
  bio: The lynchpin of the team. Amateur manga comic book artist learning frontend design. Keen DSLR photographer.
  skills: Administration, Budget monitoring, Adaptability, Multi-tasking

- avatar: phil.jpg
  name: Phil Murphy
  title: Consultant
  bio: TBC
  skills: TBC • TBC • TBC • TBC • TBC

- avatar: randal.jpg
  name: Randal Whitmore
  title: Marketing Manager
  bio: Goal-driven marketeer. Creative soul. Big believer in collaboration. People person.
  skills: Digital marketing, Multi-channel campaign marketing, Web analytics, Content production, Event production and community building
